@file:Suppress("unused")

package sandbox.kerml.root.elements

import sandbox.kerml.root.namespaces.Namespace
import sandbox.util.Validator

/**
 *
 * A `Relationship` is an [Element] that relates other [Element]. Some of its [relatedElements][relatedElement] may be
 * owned, in which case those [ownedRelatedElements][ownedRelatedElement] will be deleted from a model if their
 * [owningRelationship] is. A `Relationship` may also be owned by another [Element], in which case the
 * [ownedRelatedElements][ownedRelatedElement] of the `Relationship` are also considered to be transitively owned by the
 * [owningRelatedElement] of the `Relationship`.
 * 
 * The relatedElements of a `Relationship` are divided into source and target [Elements][Element]. The
 * `Relationship` is considered to be directed from the source to the target [Elements][Element]. An undirected
 * `Relationship` may have either all source or all target [Elements][Element].
 * 
 * A "relationship Element" in the abstract syntax is generically any [Element] that is an instance of either
 * `Relationship` or a direct or indirect specialization of `Relationship`. Any other kind of Element is a
 * "nonrelationship Element". It is a convention of that non-relationship [Elements][Element] are only related via
 * reified relationship [Elements][Element]. Any meta-associations directly between non-relationship [Elements][Element]
 * must be derived from underlying reified `Relationship`.
 */
interface Relationship : Element {
    /**
     * Whether this [Relationship] was generated by tooling to meet semantic rules, rather than being directly created
     * by a modeler.
     *
     * ```ocl
     * isImplied : Boolean
     * ```
     */
    val isImplied: Boolean

    /**
     * The [relatedElements][relatedElement] of this `Relationship` that are owned by the `Relationship`.
     * 
     * ```ocl
     * ownedRelatedElement : Element [0..*] {subsets relatedElement, ordered}
     * ```
     */
    val ownedRelatedElement: List<Element>

    /**
     * The [relatedElement] of this `Relationship` that owns the `Relationship`, if any.
     * 
     * ```ocl
     * owningRelatedElement : Element [0..1] {subsets relatedElement}
     * ```
     */
    val owningRelatedElement: Element?

    /**
     * The [Elements][Element] that are related by this `Relationship`, derived as the union of the source and target
     * [Elements][Element] of the `Relationship`.
     * 
     * ```ocl
     * relatedElement = source->union(target)
     * ```
     */
    val relatedElement: List<Element>
        get() = source + target

    /**
     * The [relatedElements][relatedElement] from which this `Relationship` is considered to be directed.
     * 
     * ```ocl
     * source : Element [0..*] {subsets relatedElement, ordered}
     * ```
     */
    val source: List<Element>

    /**
     * The [relatedElements][relatedElement] to which this `Relationship` is considered to be directed.
     * 
     * ```ocl
     * target : Element [0..*] {subsets relatedElement, ordered}
     * ```
     */
    val target: List<Element>

    /**
     * Return whether this `Relationship` has either an [owningRelatedElement] or [owningRelationship] that is a
     * library element.
     *
     * ```ocl
     * libraryNamespace() : Namespace [0..1] {redefines libraryNamespace}
     *
     * body: if owningRelatedElement <> null then owningRelatedElement.libraryNamespace()
     * else if owningRelationship <> null then owningRelationship.libraryNamespace()
     * else null endif endif
     * ```
     */
    override fun libraryNamespace(): Namespace? = if (owningRelatedElement != null) {
        owningRelatedElement!!.libraryNamespace()
    } else {
        owningRelationship?.libraryNamespace()
    }

    /**
     * If the [owningRelationship] of the `Relationship` is null but its [owningRelatedElement] is non-null, construct
     * the path using the position of the `Relationship` in the list of [ownedRelationships][owningRelationship] of its
     * [owningRelatedElement]. Otherwise, return the path of the `Relationship` as specified for an [Element] in
     * general.
     *
     * ```ocl
     * path() : String {redefines path}
     *
     * body: if owningRelationship = null and owningRelatedElement <> null then
     *     owningRelatedElement.path() + '/' +
     *     owningRelatedElement.ownedRelationship->indexOf(self).toString()
     *     -- A position index shall be converted to a decimal string representation
     *     -- consisting of only decimal digits, with no sign, leading zeros or leading
     *     -- or trailing whitespace.
     * else self.oclAsType(Element).path()
     * endif
     * ```
     */
    override fun path(): String = if (owningRelationship == null && owningRelatedElement != null) {
        owningRelatedElement!!.let { owningRelatedElement ->
            "${owningRelatedElement.path()}/${owningRelatedElement.ownedRelationship.indexOf(this)}"
        }
    } else {
        super.path()
    }

    object Validation : Validator<Relationship> {
        override val rules = Element.Validation.rules
    }
}
