package sandbox.kerml.root.elements

import sandbox.kerml.root.namespaces.Namespace

/**
 *
 * A Relationship is an Element that relates other Element. Some of its relatedElements may be owned, in
 * which case those ownedRelatedElements will be deleted from a model if their owningRelationship is. A
 * Relationship may also be owned by another Element, in which case the ownedRelatedElements of the
 * Relationship are also considered to be transitively owned by the owningRelatedElement of the
 * Relationship.
 * 
 * The relatedElements of a Relationship are divided into source and target Elements. The
 * Relationship is considered to be directed from the source to the target Elements. An undirected
 * Relationship may have either all source or all target Elements.
 * 
 * A "relationship Element" in the abstract syntax is generically any Element that is an instance of either
 * Relationship or a direct or indirect specialization of Relationship. Any other kind of Element is a "nonrelationship Element".
 * It is a convention of that non-relationship Elements are only related via reified relationship
 * Elements. Any meta-associations directly between non-relationship Elements must be derived from underlying
 * reified Relationship.
 */
@Suppress("unused")
interface Relationship : Element {
    /**
     * Whether this Relationship was generated by tooling to meet semantic rules, rather than being directly created by a
     * modeler.
     * 
     * isImplied : Boolean
     */
    val isImplied: Boolean

    /**
     * The relatedElements of this Relationship that are owned by the Relationship.
     * 
     * `ownedRelatedElement : Element [0..*] {subsets relatedElement, ordered}`
     */
    val ownedRelatedElement: List<Element>

    /**
     * The relatedElement of this Relationship that owns the Relationship, if any.
     * 
     * `owningRelatedElement : Element [0..1] {subsets relatedElement}`
     */
    val owningRelatedElement: Element?

    /**
     * The Elements that are related by this Relationship, derived as the union of the source and target Elements of the
     * Relationship.
     * 
     * `/relatedElement : Element [0..*] {ordered, nonunique}`
     * 
     * Constraint:
     * - deriveRelationshipRelatedElement
     *     The relatedElements of a Relationship consist of all of its source Elements followed by all of its target
     *     Elements.
     *     ```ocl
     *     relatedElement = source->union(target)
     *     ```
     */
    val relatedElement: List<Element>
        get() = source + target

    /**
     * The relatedElements from which this Relationship is considered to be directed.
     * 
     * `source : Element [0..*] {subsets relatedElement, ordered}`
     */
    val source: List<Element>

    /**
     * The relatedElements to which this Relationship is considered to be directed.
     * 
     * `target : Element [0..*] {subsets relatedElement, ordered}`
     */
    val target: List<Element>

    /**
     * Return whether this Relationship has either an owningRelatedElement or owningRelationship that is a
     * library element.
     * 
     * `libraryNamespace() : Namespace [0..1] {redefines libraryNamespace}`
     * ```ocl
     * body: if owningRelatedElement <> null then owningRelatedElement.libraryNamespace()
     * else if owningRelationship <> null then owningRelationship.libraryNamespace()
     * else null endif endif
     * ```
     */
    override fun libraryNamespace(): Namespace? = if (owningRelatedElement != null) {
        owningRelatedElement!!.libraryNamespace()
    } else {
        owningRelationship?.libraryNamespace()
    }

    /**
     * If the owningRelationship of the Relationship is null but its owningRelatedElement is non-null, construct
     * the path using the position of the Relationship in the list of ownedRelationships of its
     * owningRelatedElement. Otherwise, return the path of the Relationship as specified for an Element in
     * general.
     * 
     * `path() : String {redefines path}`
     * ```ocl
     * body: if owningRelationship = null and owningRelatedElement <> null then
     * owningRelatedElement.path() + '/' +
     * owningRelatedElement.ownedRelationship->indexOf(self).toString()
     * -- A position index shall be converted to a decimal string representation
     * -- consisting of only decimal digits, with no sign, leading zeros or leading
     * -- or trailing whitespace.
     * else self.oclAsType(Element).path()
     * endif
     * ```
     */
    override fun path(): String = if (owningRelationship == null && owningRelatedElement != null) {
        owningRelatedElement!!.let { owningRelatedElement ->
            "${owningRelatedElement.path()}/${owningRelatedElement.ownedRelationship.indexOf(this)}"
        }
    } else {
        super.path()
    }
}
